// Full UK coverage:
//  - England: the 48 ceremonial counties (Lieutenancies Act 1997)
//  - Scotland: the 32 council areas
//  - Wales: the 22 principal areas
//  - Northern Ireland: the 6 traditional counties
//
// 108 entries, alphabetical. Use this list everywhere an "area" appears
// in the UI — never a free text input — so filters stay deterministic.

export const UK_COUNTIES = [
  "Aberdeen City",
  "Aberdeenshire",
  "Angus",
  "Antrim",
  "Argyll and Bute",
  "Armagh",
  "Bedfordshire",
  "Berkshire",
  "Blaenau Gwent",
  "Bridgend",
  "Bristol",
  "Buckinghamshire",
  "Caerphilly",
  "Cambridgeshire",
  "Cardiff",
  "Carmarthenshire",
  "Ceredigion",
  "Cheshire",
  "City of Edinburgh",
  "City of London",
  "Clackmannanshire",
  "Conwy",
  "Cornwall",
  "County Durham",
  "Cumbria",
  "Denbighshire",
  "Derbyshire",
  "Devon",
  "Dorset",
  "Down",
  "Dumfries and Galloway",
  "Dundee City",
  "East Ayrshire",
  "East Dunbartonshire",
  "East Lothian",
  "East Renfrewshire",
  "East Riding of Yorkshire",
  "East Sussex",
  "Essex",
  "Falkirk",
  "Fermanagh",
  "Fife",
  "Flintshire",
  "Glasgow City",
  "Gloucestershire",
  "Greater London",
  "Greater Manchester",
  "Gwynedd",
  "Hampshire",
  "Herefordshire",
  "Hertfordshire",
  "Highland",
  "Inverclyde",
  "Isle of Anglesey",
  "Isle of Wight",
  "Kent",
  "Lancashire",
  "Leicestershire",
  "Lincolnshire",
  "Londonderry",
  "Merseyside",
  "Merthyr Tydfil",
  "Midlothian",
  "Monmouthshire",
  "Moray",
  "Na h-Eileanan Siar",
  "Neath Port Talbot",
  "Newport",
  "Norfolk",
  "North Ayrshire",
  "North Lanarkshire",
  "North Yorkshire",
  "Northamptonshire",
  "Northumberland",
  "Nottinghamshire",
  "Orkney Islands",
  "Oxfordshire",
  "Pembrokeshire",
  "Perth and Kinross",
  "Powys",
  "Renfrewshire",
  "Rhondda Cynon Taf",
  "Rutland",
  "Scottish Borders",
  "Shetland Islands",
  "Shropshire",
  "Somerset",
  "South Ayrshire",
  "South Lanarkshire",
  "South Yorkshire",
  "Staffordshire",
  "Stirling",
  "Suffolk",
  "Surrey",
  "Swansea",
  "Torfaen",
  "Tyne and Wear",
  "Tyrone",
  "Vale of Glamorgan",
  "Warwickshire",
  "West Dunbartonshire",
  "West Lothian",
  "West Midlands",
  "West Sussex",
  "West Yorkshire",
  "Wiltshire",
  "Worcestershire",
  "Wrexham",
] as const;

export type UKCounty = (typeof UK_COUNTIES)[number];

const COUNTY_SET = new Set<string>(UK_COUNTIES);

export function isUKCounty(value: unknown): value is UKCounty {
  return typeof value === "string" && COUNTY_SET.has(value);
}
